cabal-version: 1.12

name:           web-handler
version:        0.0.0.1
author:         Jordi Forga Alberich
build-type:     Simple

library
  exposed-modules:
    Handler
    Handler_T1
    Handler_T2
  build-depends:
    base >=4.7 && <5,
    blaze-html,
    bytestring,
    containers,
    cookie,
    http-types,
    mtl,
    text,
    wai >=3.0
  default-language: Haskell2010

executable hello-2
  main-is:
    hello-2.hs
  other-modules:
    Handler
  build-depends:
    base >=4.7 && <5,
    blaze-html,
    bytestring,
    cookie,
    http-types,
    mtl,
    text,
    wai >=3.0,
    warp
  default-language: Haskell2010
