
cabal-version: 1.12

name:           http-serve
version:        0.1.1.0
author:         Jordi Forga Alberich
build-type:     Simple

executable http-serve
  main-is:
      Main.hs
  if impl(ghcjs) || arch(javascript)
    buildable:
      False
  build-depends:
      base >=4.7 && <5,
      bytestring,
      mime-types,
      wai <3.3,
      wai-app-static,
      warp <3.5
  ghc-options: -threaded
  default-language:
    Haskell2010

