name:                 drawing-activity
version:              0.2.1.0
visibility:           public
id:                   drawing-activity-0.2.1.0-kReMUMqGaJ3uR4VYKBusw
key:                  drawing-activity-0.2.1.0-kReMUMqGaJ3uR4VYKBusw
license:              BSD-3-Clause
copyright:            2022 Jordi Forga-Alberich
maintainer:           jordi.forga@upc.edu
author:               Jordi Forga Alberich
abi:                  feb366405d91cb43633e17b08ec9a0ff
exposed:              True
exposed-modules:
    Drawing.Activity Drawing.Activity.StableNamed
    Drawing.Activity.Timer

hidden-modules:       Drawing.Activity.Internal.Event
import-dirs:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/lib/x86_64-linux-ghc-9.2.8/drawing-activity-0.2.1.0-kReMUMqGaJ3uR4VYKBusw

library-dirs:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/lib/x86_64-linux-ghc-9.2.8/drawing-activity-0.2.1.0-kReMUMqGaJ3uR4VYKBusw

dynamic-library-dirs:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/lib/x86_64-linux-ghc-9.2.8

data-dir:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/share/x86_64-linux-ghc-9.2.8/drawing-activity-0.2.1.0

hs-libraries:         HSdrawing-activity-0.2.1.0-kReMUMqGaJ3uR4VYKBusw
depends:
    aeson-2.0.3.0-B56EwkCboVUIb59k2pHz9h base-4.16.4.0
    bytestring-0.11.4.0 containers-0.6.5.1
    drawing-core-0.1.2.0-CMoufQkZW8a3C0lyxSOCL7
    http-types-0.12.3-DOjHG19CWso9L585xkx2dm
    jsaddle-0.9.9.3-9I3ZTStxodi8MqiyDocDVs
    jsaddle-warp-extra-0.1.0.0-Geb10a30eLDFg4eXn1WXXG
    miso-1.8.7.0-FuVlAq9Bf1p3nNl4vifLkG mtl-2.2.2 text-1.2.5.0
    time-1.11.1.1

haddock-interfaces:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/doc/drawing-activity-0.2.1.0/drawing-activity.haddock

haddock-html:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/doc/drawing-activity-0.2.1.0
