name:                 drawing-core
version:              0.1.2.0
visibility:           public
id:                   drawing-core-0.1.2.0-CMoufQkZW8a3C0lyxSOCL7
key:                  drawing-core-0.1.2.0-CMoufQkZW8a3C0lyxSOCL7
license:              BSD-3-Clause
copyright:            2022 Jordi Forga-Alberich
maintainer:           jordi.forga@upc.edu
author:               Jordi Forga Alberich
abi:                  88e06b23bf0b15605a7748b3cffa3591
exposed:              True
exposed-modules:
    Drawing Drawing.IO Drawing.Image Drawing.Render Drawing.Types
    Drawing.Vector

import-dirs:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/lib/x86_64-linux-ghc-9.2.8/drawing-core-0.1.2.0-CMoufQkZW8a3C0lyxSOCL7

library-dirs:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/lib/x86_64-linux-ghc-9.2.8/drawing-core-0.1.2.0-CMoufQkZW8a3C0lyxSOCL7

dynamic-library-dirs:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/lib/x86_64-linux-ghc-9.2.8

data-dir:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/share/x86_64-linux-ghc-9.2.8/drawing-core-0.1.2.0

hs-libraries:         HSdrawing-core-0.1.2.0-CMoufQkZW8a3C0lyxSOCL7
depends:
    aeson-2.0.3.0-B56EwkCboVUIb59k2pHz9h base-4.16.4.0
    base64-bytestring-1.2.1.0-APmD3ny5xOU8uSlwgDmyWU
    bytestring-0.11.4.0 template-haskell-2.18.0.0 text-1.2.5.0

haddock-interfaces:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/doc/drawing-core-0.1.2.0/drawing-core.haddock

haddock-html:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/doc/drawing-core-0.1.2.0
