name:                 jsaddle-warp-extra
version:              0.1.0.0
visibility:           public
id:                   jsaddle-warp-extra-0.1.0.0-Geb10a30eLDFg4eXn1WXXG
key:                  jsaddle-warp-extra-0.1.0.0-Geb10a30eLDFg4eXn1WXXG
author:               Jordi Forga Alberich
abi:                  cd51038fd2005532e665d02db124c940
exposed:              True
exposed-modules:      Language.Javascript.JSaddle.RunWarp
import-dirs:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/lib/x86_64-linux-ghc-9.2.8/jsaddle-warp-extra-0.1.0.0-Geb10a30eLDFg4eXn1WXXG

library-dirs:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/lib/x86_64-linux-ghc-9.2.8/jsaddle-warp-extra-0.1.0.0-Geb10a30eLDFg4eXn1WXXG

dynamic-library-dirs:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/lib/x86_64-linux-ghc-9.2.8

data-dir:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/share/x86_64-linux-ghc-9.2.8/jsaddle-warp-extra-0.1.0.0

hs-libraries:         HSjsaddle-warp-extra-0.1.0.0-Geb10a30eLDFg4eXn1WXXG
depends:
    base-4.16.4.0 binary-0.8.9.0 bytestring-0.11.4.0 containers-0.6.5.1
    http-types-0.12.3-DOjHG19CWso9L585xkx2dm
    jsaddle-0.9.9.3-9I3ZTStxodi8MqiyDocDVs
    jsaddle-warp-0.9.9.5-GWGPpEd25yK48yAR3wXDbL mtl-2.2.2 text-1.2.5.0
    wai-3.2.3-6cJyfzEcrgBFdELHC2w5IA warp-3.3.23-JA0u0CSeDoBKkFPNQ80cBG
    websockets-0.12.7.3-6m2nqozEyDvBTte5J15ND6

haddock-interfaces:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/doc/jsaddle-warp-extra-0.1.0.0/jsaddle-warp-extra.haddock

haddock-html:
    /home/bigweld/Repos/DAT-haskell-web-app-design/lab2/dat-prj/.stack-work/install/x86_64-linux/61512f0f2d995b12a2d04bd30ec6068d08e57c6f21de2a1cc19b32b4d72b35ed/9.2.8/doc/jsaddle-warp-extra-0.1.0.0
